Inc 13
abogushev/yametrics pull request #14
Opened 2022-08-10 05:42 UTC by abogushev

2022-08-13 08:27 UTC, bambruysk requested changes
очень хорошою Единственное замечание это к  БД

2022-08-13 08:27 UTC, bambruysk commented on cmd/server/main.go
> +	if dbURL := cfgProvider.StorageCfg.DBURL; dbURL != "" {
Здесь же можно сразу сравнить? Кстати, более гибкий вариант len(cfgProvider.StorageCfg.DBURL) != 0 - тогда он будет работать со слайсом байт или строк

2022-08-13 08:27 UTC, bambruysk commented on internal/server/handlers/handlers.go
> +func NewHandler(
можно ли сделать Handler - приватным? И другие структуры? Если можно то лучще сделатю В большинстве случаев можно

2022-08-13 08:27 UTC, bambruysk commented on internal/server/storage/DbMetricsStorage.go
> +	_, err := db.xdb.ExecContext(db.ctx, "create table if not exists metrics(id varchar not null primary key, mtype varchar not null, delta bigint, value double precision)")
лучше sql - запросы вынести в отдельные константы, если использовать `` то можно их прилично отформатировать

2022-08-13 08:27 UTC, bambruysk commented on internal/server/storage/DbMetricsStorage.go
> +		return err
ошибки лучше логгировать, и обернуть в свои

2022-08-13 08:27 UTC, bambruysk commented on internal/server/storage/DbMetricsStorage.go
> +		if _, err = db.xdb.ExecContext(db.ctx, "update metrics set mtype = $1, delta = $2, value = $3 where id = $4", m.MType, m.Delta, m.Value, m.ID); err != nil {
здесь можно проще - с меньшим количеством походов в базу 
set delta = delta + $2 
количество измененных рядов - то есть было ли вообще что-то там найдено можно получить из первого параметра, 
Кроме того когда в одном методе исполняется несколько запросов возникает та же гонка данных - то есть параллельно кто-то еще может писать ту же метрику. И запрос на создание insert - может уткнуться в уже созданную запись.  Тут два варианта - если между запросами делается какая-то бизнес-логика - то имспользуем транзакцию, либо попытаться решить все в один запрос. В данном случае это просто https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/

2022-08-13 08:27 UTC, bambruysk commented on internal/server/storage/DbMetricsStorage.go
> +		if _, err = db.xdb.ExecContext(db.ctx, "update metrics set mtype = $1, delta = $2, value = $3 where id = $4", m.MType, m.Delta, m.Value, m.ID); err != nil {
усмотрелБ в препаред стейтменте то же, можно просто использовпть его

2022-08-13 08:27 UTC, bambruysk commented on internal/server/storage/DbMetricsStorage.go
> +	return tx.Commit()
после коммита выполнится еще и роллбек, это не очень хорошо

2022-08-13 08:27 UTC, bambruysk commented on internal/server/storage/DbMetricsStorage.go
> +	} else {
else - лишеее

2022-08-14 05:10 UTC, abogushev commented on internal/server/storage/DbMetricsStorage.go
> +	return tx.Commit()
брал из лекции "Запись в базу данных, стейтменты и транзакции"

2022-08-18 19:43 UTC, bambruysk approved these changes
Можно сливать - приянто)

2022-08-20 05:05 UTC, merged